CREATE DATABASE NEWS;

CREATE USER 'etl'@'XXXXXXXX' IDENTIFIED BY 'VeggieDiner&';
CREATE USER 'news'@'XXXXXXXX' IDENTIFIED BY 'MeatLovers#';

-- Using VPC IP segment for AWS Lambda access control
GRANT SELECT, INSERT, DELETE, UPDATE, EXECUTE ON NEWS.* TO 'etl'@'XXXXXXXXX';
GRANT SELECT, INSERT, DELETE, UPDATE, EXECUTE ON NEWS.* TO 'news'@'XXXXXXXXX';

FLUSH PRIVILEGES;