USE NEWS;

CREATE TABLE IF NOT EXISTS AGGREGATE_CATEGORY (
   NEWS_DAY             VARCHAR(8) NOT NULL UNIQUE,
   DAY_OF_WEEK          VARCHAR(8) NOT NULL,
   CATEGORY             VARCHAR(30) NOT NULL,
   NEWS_COUNT           INT NOT NULL,
   PRIMARY KEY ( NEWS_DAY ),
   INDEX ( DAY_OF_WEEK ),
   INDEX ( CATEGORY )
);

CREATE TABLE IF NOT EXISTS AGGREGATE_SENTIMENT (
   NEWS_DAY             VARCHAR(8) NOT NULL UNIQUE,
   DAY_OF_WEEK          VARCHAR(8) NOT NULL,
   SENTIMENT             VARCHAR(30) NOT NULL,
   NEWS_COUNT           INT NOT NULL,
   PRIMARY KEY ( NEWS_DAY ),
   INDEX ( DAY_OF_WEEK ),
   INDEX ( SENTIMENT )
);

CREATE TABLE IF NOT EXISTS AGGREGATE_TOPIC (
   NEWS_DAY             VARCHAR(8) NOT NULL UNIQUE,
   DAY_OF_WEEK          VARCHAR(8) NOT NULL,
   TOPIC             VARCHAR(30) NOT NULL,
   NEWS_COUNT           INT NOT NULL,
   PRIMARY KEY ( NEWS_DAY ),
   INDEX ( DAY_OF_WEEK ),
   INDEX ( TOPIC )
);

CREATE TABLE IF NOT EXISTS AGGREGATE_TAG (
   NEWS_DAY             VARCHAR(8) NOT NULL UNIQUE,
   DAY_OF_WEEK          VARCHAR(8) NOT NULL,
   TAG             VARCHAR(30) NOT NULL,
   NEWS_COUNT           INT NOT NULL,
   PRIMARY KEY ( NEWS_DAY ),
   INDEX ( DAY_OF_WEEK ),
   INDEX ( TAG )
);

CREATE TABLE IF NOT EXISTS AGGREGATE_INTERACTION (
   INTERACTION_DAY             VARCHAR(8) NOT NULL UNIQUE,
   DAY_OF_WEEK                 VARCHAR(8) NOT NULL,
   NEWS_METADATA_KEY           VARCHAR(20) NOT NULL,
   NEWS_METADATA_VALUE         VARCHAR(100) NOT NULL,
   PREVIOUS_METADATA_VALUE     VARCHAR(100) NOT NULL,
   INTERACTION_COUNT           INT NOT NULL,
   PRIMARY KEY ( INTERACTION_DAY ),
   INDEX ( DAY_OF_WEEK, NEWS_METADATA_KEY, NEWS_METADATA_VALUE )
);

CREATE TABLE IF NOT EXISTS NEWS_MAP (
   NEWS_UUID             VARCHAR(100) NOT NULL UNIQUE,
   NEWS_METADATA_KEY     VARCHAR(20) NOT NULL,
   NEWS_METADATA_VALUE   VARCHAR(100) NOT NULL,
   PRIMARY KEY ( NEWS_UUID ),
   INDEX ( NEWS_METADATA_KEY ),
   INDEX ( NEWS_METADATA_VALUE ),
   INDEX ( NEWS_METADATA_KEY, NEWS_METADATA_VALUE )
);

CREATE TABLE IF NOT EXISTS NEWS (
   NEWS_UUID              VARCHAR(100) NOT NULL UNIQUE,
   NEWS_DAY               VARCHAR(8) NOT NULL UNIQUE,
   NEWS_TITLE             VARCHAR(100) NOT NULL,
   NEWS_CONTEXT           LONGTEXT NOT NULL,
   RATING                 INT NOT NULL,
   PRIMARY KEY ( NEWS_UUID ),
   INDEX ( NEWS_DAY )
);